import type { Metadata } from "next";

 import localFont from "next/font/local";

import "./globals.css";

    const Normal = localFont({
      src: "fonts/FOT-Rodin Pro M/FOT-Rodin Pro M.otf", // Path relative to the file where localFont is called
      display: "swap", // Optional: controls font display behavior
    });
    
    export const SemiBold = localFont({
      src: "fonts/FOT-Rodin Pro DB/FOT-Rodin Pro DB.otf", // Path relative to the file where localFont is called
      display: "swap", // Optional: controls font display behavior
    });

    export const Header = localFont({
      src: "fonts/FOT-Rodin Pro B/FOT-Rodin Pro B.otf", // Path relative to the file where localFont is called
      display: "swap", // Optional: controls font display behavior
    });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Normal.className}>
        {children}
      </body>
    </html>
  );
}


